device: cuda

model:
  in_channels: 1
  out_channels: 1
  n_hiddens: 128
  downsample: [4, 4, 4]
  num_groups: 32
  embedding_dim: 256
  n_codes: 512
  no_random_restart: false
  restart_thres: 1.0

data:
  data_dir: Data/Preprocessed-Data
  train_split: 0.7
  val_split: 0.15
  num_workers: 2
  pin_memory: false
  use_patches: true
  patch_size: [64, 64, 64]
  stride: [64, 64, 64]
  
optimizer:
  lr: 0.00005
  weight_decay: 0.0001
  lr_min: 1.0e-7

training:
  epochs: 50
  batch_size: 16
  save_dir: checkpoints/vqvae
  checkpoint_interval: 1
  use_amp: true
  accumulation_steps: 4
